spring.profiles.active: local

spring:
  config:
    import:
      - persistence.yml


  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true

PSP:
  toss:
    secretKey: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
    url: https://api.tosspayments.com
