spring.profiles.active: local

spring:
  config:
    import:
      - persistence.yml
      - client.yml


  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
